### ISSUE TITLE
Inline Feedback not appearing on second visit

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt-contrib-tutor#80]
### Subject of the issue
Question feedback does not automatically display for an answered question when visiting a page for the second time (in or out of session) when the `_type` property is set to `inline`

### Your environment
* v5.x FW / AAT

### Steps to reproduce
* 'show feedback' button starts disabled because question feedback inline is set (usually, because of this we hide the show feedback button)
* user answers question, feedback is shown and all is well
* user goes to another page and then returns to the question they have just answered in the previous page
* question feedback is missing
* reason: on page revisit, the 'show feedback' button is now active and needs to be selected to reveal the question feedback

### Expected behaviour
* ideal solution: if type inline is selected for question feedback, question feedback auto shows without requiring user to select 'show feedback' button

**Comment by chris-steele** [comment]
It's easy enough to implement the expected behaviour, but note that the user may click 'hide feedback' and so automatically opening the feedback on return to the page may not be desirable. We would need to record a new piece of state to honour the user's choice of whether to show or hide (inline) feedback.

Looking into this highlighted some variable behaviour across Adapt components. For example, when returning to a page (in-session) a narrative component will display the last selected item, but an accordion component will not expand the last selected item.

Thoughts on how we should proceed?

**Comment by guywillis** [comment]
If the inline feedback type is selected then I would imagine we should remove both the show and hide feedback buttons ensuring that once a user has answered a question they will always see the feedback.

**Comment by danielghost** [comment]
I have implemented this for a propject already, so will reassign to myself and create a PR.
